version: '3'

services:
  db:
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: Wediary_development
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/db:/var/lib/mysql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    # pry-byebugを使えるようにする
    tty: true 
    stdin_open: true
    depends_on:
      - db # DB側のコンテナが出来上がってからwebを実行する
    ports:
      - "0.0.0.0:3000:3000" # ホストからゲストへポートフォワード
    volumes:
      - .:/Wediary # ソースコード変更したらDocker側も即反映されるように