version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3-node-browsers
    steps:
      - checkout
      - run:
          name: update bundler
          command: |
            gem update --system
            gem install bundler
      - run: bundle install
      - run: 
        name: docker-compose run web rails db:create db:migrate
        command: |
            docker-compose run web bin/rails db:create db:migrate
      - run: 
        name: docker-compose run web bundle exec rspec
        command: |
            docker-compose run web bundle exec rspec