version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3-node-browsers
    working_directory: ~/Wediary
    steps:
      - checkout
      - run:
          name: update bundler
          command: |
            gem update --system
            gem install bundler
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
            
      - run: docker-compose run web bundle install
      
      
      - run:
          name: rails db:create and db:migrate
          command: docker-compose run web bin/rails db:create db:migrate
          
      - run:
          name: rails db:migrate RAILS_ENV=test
          command: docker-compose run web bin/rails db:migrate RAILS_ENV=test
          
      - run:
          name: docker-compose run web yarn Install
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: docker-compose run web yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
          
      # - run:
      #     name: yarn remove @rails/webpacker
      #     command: docker-compose run web yarn remove @rails/webpacker
          
      # - run:
      #     name: rm files related to webpacker
      #     command: |
      #       docker-compose run web rm -r config/webpack
      #       docker-compose run web rm config/webpacker.yml
      #       docker-compose run web rm bin/webpack
      #       docker-compose run web rm bin/webpack-dev-server
            
      # - run:
      #     name: docker-compose run web bin/rails webpacker:install
      #     command: docker-compose run web bin/rails webpacker:install
      
      # - run:
      #     name: docker-compose run web bundle exec bin/webpack
      #     command: docker-compose run web bundle exec bin/webpack
      # - run:
      #     name: docker-compose run web bundle exec bin/rails yarn add @rails/webpacker@5.2.1 from "."
      #     command: docker-compose run web bundle exec bin/rails yarn add @rails/webpacker@5.2.1 from "."
          
      # - run:
      #     name: docker-compose run web bundle exec bin/rails yarn add --dev webpack-dev-server from "."
      #     command: docker-compose run web bundle exec bin/rails yarn add --dev webpack-dev-server from "."
      
      - run:
          name: d-c build
          command: docker-compose build
          
          
            
      - run:
          name: docker-compose up
          command: |
            set -x
            docker-compose up -d
            
          
      - run:
          name: test
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob 'spec/**/*_spec.rb' | circleci tests split --split-by=timings)"
            docker-compose run web bundle exec rspec --format progress \
                                                                  --format RspecJunitFormatter \
                                                                  --out /tmp/test-results/rspec.xml \
                                                                  $TEST_FILES
      - run:
          name: docker-compose down
          command: docker-compose down